/**
 * Gfycat-like human-friendly ID generator
 * @returns {string} ID
 */
function makeID(){
	const words = 'aero,alabaster,alizarin,almond,amaranth,amazon,amber,amber,amethyst,ao,apricot,aqua,aquamarine,artichoke,asparagus,auburn,aureolin,avocado,azure,azure,beaver,beige,bisque,bistre,bittersweet,black,blue,blue,blue,blue,blue,blue,blueberry,blush,bole,bone,bronze,brown,brown,buff,burgundy,burlywood,byzantine,byzantium,cadet,calypso,camel,cardinal,carmine,carnelian,catawba,celadon,celeste,cerise,cerulean,cerulean,champagne,charcoal,chartreuse,chartreuse,chestnut,chocolate,chocolate,cinereous,citrine,citron,claret,coconut,coffee,copper,coquelicot,coral,cordovan,cornsilk,cream,crimson,crimson,cultured,cyan,cyclamen,dandelion,denim,desert,diamond,dirt,ebony,ecru,eggplant,eggshell,emerald,eminence,eucalyptus,fallow,fandango,fawn,feldgrau,firebrick,flame,flax,flirt,frostbite,fuchsia,fuchsia,fulvous,gainsboro,gamboge,garnet,glaucous,gold,gold,gold,gold,goldenrod,gray,gray,green,green,green,green,green,green,green,green,grullo,gunmetal,harlequin,heliotrope,honeydew,iceberg,icterine,inchworm,independence,indigo,iris,irresistible,isabelline,ivory,jade,jasmine,jet,jonquil,keppel,khaki,khaki,kobe,kobi,kobicha,lanzones,lava,lavender,lavender,lemon,lenurple,liberty,licorice,lilac,lime,lime,limerick,linen,lion,liver,liver,liver,livid,lotion,lumber,lust,magenta,magenta,mahogany,maize,maize,malachite,manatee,mandarin,mango,mantis,marigold,maroon,maroon,maroon,mauve,mauvelous,melon,melon,menthol,midnight,milk,mindaro,ming,mint,moccasin,mocha,moonstone,mud,mulberry,mulberry,mustard,mystic,nickel,nyanza,ochre,olive,olivine,onyx,opal,orange,orange,orange,orange,orange,orange,orchid,orchid,oxblood,oxley,parchment,patriarch,peach,peach,pear,pearl,peridot,periwinkle,periwinkle,persimmon,peru,petal,phlox,pineapple,pink,pink,pistachio,platinum,plum,plum,popstar,prune,puce,pumpkin,purple,purple,purple,purpureus,quartz,quincy,rackley,rajah,raspberry,razzmatazz,red,red,red,red,red,red,red,redwood,rhythm,rose,rosewood,ruber,ruby,rufous,rum,russet,rust,saffron,sage,salem,salmon,sand,sandstorm,sapphire,scarlet,scarlet,seashell,sepia,shadow,shampoo,shandy,sienna,silver,silver,silver,sinopia,skobeloff,smalt,smitten,smoke,snow,soap,straw,strawberry,sunglow,sunny,sunray,sunset,taffy,tan,tan,tangelo,tangerine,taupe,teal,telemagenta,temptress,tenné,thistle,thistle,timberwolf,titanium,tomato,toolbox,tooth,topaz,tulip,tumbleweed,turquoise,tuscan,tuscany,ube,ultramarine,umber,urobilin,vanilla,verdigris,vermilion,vermilion,veronica,violet,violet,violet,violet,violet,violet,viridian,water,watermelon,waterspout,wenge,wheat,white,wine,wisteria,xanadu,yellow,yellow,yellow,yellow,yellow,yellow,yellow,zaffre,zinnwaldite,zomp'.split(',')
	
	return new Array(3).fill(words).map(randomElement).join('-')
}
